on:
  push:
    branches:
      - master

name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer
        run: |
          composer validate
      
      - name: Install dependencies
        run: |
          composer install --optimize-autoloader --prefer-dist --no-progress --no-suggest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get AWS ECR credentials
        id: ecr-credentials
        run: |
          echo "::set-output name=username::AWS"
          echo "::set-output name=password::`aws ecr get-login-password`"

      - name: Docker build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: reponame
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker-compose build
          docker tag laravel-docker-aws-app:latest 442976946845.dkr.ecr.ap-south-1.amazonaws.com/laravel-docker-aws-app:latest
          docker tag laravel-docker-aws-nginx:latest 442976946845.dkr.ecr.ap-south-1.amazonaws.com/laravel-docker-aws-nginx:latest          docker tag larvel-docker-aws-app:$IMAGE_TAG $ECR_REGISTRY/larvel-docker-aws-app:$IMAGE_TAG
          docker push 442976946845.dkr.ecr.ap-south-1.amazonaws.com/laravel-docker-aws-app:latest
          docker push 442976946845.dkr.ecr.ap-south-1.amazonaws.com/laravel-docker-aws-nginx:latest

      - name: Download task def
        run: |
          aws ecs describe-task-definition --task-definition conference --query taskDefinition > task-definition.json

      - name: Render Amazon ECS task definition for container
        id: render-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: conference
          image: ${{ steps.login-ecr.outputs.registry }}/conference:${{ github.sha }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-container.outputs.task-definition }}
          service: conference
          cluster: conference
          wait-for-service-stability: true